name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare docs folder
        run: |
          rm -rf docs
          mkdir -p docs
          cp index.html docs/
          cp articles.html docs/
          cp map.html docs/
          cp admin.html docs/
          cp post.html docs/
          cp posts-db.json docs/
          cp -r assets docs/
          cp -r posts docs/
          cp -r gpx docs/

      - name: Commit and push docs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Deploy: update docs folder" && git push)
